before_install:
  - env
  - lsb_release -a
  - uname -a
  - sudo apt-get -qq update

script:
  # master
  - ./install.sh -p /tmp/jubatus
  - rm -rf /tmp/jubatus
  # develop
  - ./install.sh -p /tmp/jubatus -D
  - rm -rf /tmp/jubatus
  # develop with re2
  - ./install.sh -p /tmp/jubatus -D -r
  - rm -rf /tmp/jubatus

branches:
  only:
    - master
    - develop

notifications:
  email: false
